### ISSUE TITLE
Execution of 7z binary hangs for existing output files

### ISSUE THREAD

**Issue by pgiblock** [wummel/patool#24] opened 2015-07-28 05:39 UTC
7z prompts the user to confirm whether an existing file should be overwritten. This cause the process to hang since the user is unable to supply a response to the 7z process. The program supports the `-y` option to answer yes to all prompts; overwriting all existing output files. patool should supply `-y` if the 7z binary is used in order to make the behavior consistent with other tools such as gunzip and tar.

**Comment by pgiblock** [comment] 2015-07-28 06:20
unrar has the same issue with the same fix. I'm currently working around this by patching the relevant patoolib.program.*.extract_* files at runtime.

**Comment by wummel** [comment] 2015-12-05 11:33
I am wondering how this happens since patool extracts archive files to a unique and freshly created output directory (starting with Unpack_). Are there perhaps duplicate files in the archive?

**Comment by wummel** [comment] 2015-12-06 19:51
We believe that the issue you reported is fixed in the source repository of patool which can be found under:
https://github.com/wummel/patool

Changelog entry:
* Added new option --non-interactive to avoid commandline prompts of
  archive programs.
  Closes: GH bug #16, #24

Thank you for reporting the issue. It is now marked as fixed. If you believe that the issue is not fixed appropriately just add a comment to this issue.

**Comment by wummel** [comment] 2015-12-07 11:33
A new version 1.9 of patool has been released on 07.12.2015.
Therefore this bug will be closed. If you think this issue is not solved, please open a new issue.

**Closed by wummel** 2015-12-07 11:33 UTC
Labels: fixed, question
