### ISSUE TITLE
patoolib dosent work with big archive

### ISSUE THREAD

**Issue by AlexiJemano** [wummel/patool#156] opened 2024-03-31 17:41 UTC
So I  have an arhive (18gb) and it only extracts about 8gb it dosent give a error and it says that the extraction was susseful.
(I tried with smaller files and it worked)

**Comment by wummel** [comment] 2024-07-03 18:54
Can you give a little more infos on this, for example debug output, or at least the archive format and operating system you are using.

**Comment by wummel** [comment] 2024-09-25 09:11
I cannot reproduce this, and there is no more info on this. I suspect this has something to do with restrictions of the operation system, file system or the unpack program. Closing.

**Closed by wummel** 2024-09-25 09:11 UTC
