### ISSUE TITLE
file `D' was not found

### ISSUE THREAD

**Issue by muhammedfurkan** [wummel/patool#79] opened 2019-11-23 20:04 UTC
how can I fix that

**Comment by yarikoptic** [comment] 2019-11-23 22:44
Bug wasn't found, closing.

On a serious note - provide details, eg how we could replicate and what version of patool you are using

**Comment by wummel** [comment] 2023-10-26 19:05
Closing, if you still have problems with a newer version of patool you can file a new issue.

**Closed by wummel** 2023-10-26 19:05 UTC

**Comment by Mips96** [comment] 2023-11-15 01:20
I had the same issue with `create_archive()`. The problem is that the second parameter (the list of files/folders that should be zipped) can be in a tuple as indicated in the readme _if_ there are multiple files/folders. But if you try to zip only one file, it has to be in a list. Otherwise, you get an error along the lines of `file [the first letter of your filename] was not found`, which in OP's case was D. This is also referred to in issue #123.
