### ISSUE TITLE
Auto fix filename encoding in zipfiles when extracting

### ISSUE THREAD

**Issue by proItheus** [wummel/patool#168] opened 2024-10-20 09:33 UTC
Sometimes the filenames extracted by patool from zips are corrupted.

As the readme of https://github.com/Dragon2fly/ZipUnicode says:

>For different languages, Windows uses different code pages to encode filename. So, if you create a zip file containing a file named ê.txt on Linux and extract it on Windows, you may got something like ├¬.txt or ﾃｪ.txt.
...
The same thing also happens when a zip file was created on Windows, contains non-ascii filename, and then extracted on Linux or on Windows that use different code pages.

So can we auto-detect and fix (translate them to utf8) filenames in zipfiles when extracting? (Maybe adding a flag --fix?)

**Comment by harkabeeparolus** [comment] 2024-10-20 11:45
Does this bug only happen when you use patool? Or can you also reproduce it with unzip or 7z without using patool?

**Comment by proItheus** [comment] 2024-10-20 13:03
Yes, it happens with unzip or 7z. I'd rather say it's a bug of the zip format, not specifying filenames encodings, than a bug of some software.

**Comment by harkabeeparolus** [comment] 2024-10-21 11:52
I know about [ftfy (Fixes Text For You)](https://github.com/rspeer/python-ftfy), a Python package here on GitHub that tries to fix encoding problems in the more general case.

However, looking at ftfy, this does not seem like a trivial algorithm if it is to be generally useful. And I'm not advocating bringing ftfy on as a dependency... But the complexity of ftfy suggests that this is probably not an easy, simple fix.

**Comment by wummel** [comment] 2024-10-23 05:54
This is an interesting problem, but I believe it is not a good fit for patool.

Implementing this for the [internal extractor](https://github.com/wummel/patool/blob/master/patoolib/programs/py_zipfile.py) would require these steps:
- read all filename entries, and detect if any of them does not have a unicode entry (checking if the utf8 flag is set or not)
- try to detect the filename encoding automatically with chardet.
- if detected, fix the filenames while extracting
Basically, it means copying and/or reimplementing the code from the ZipUnicode repo mentioned above.

The downsides of this approach:
- only the internal zip extractor using the Python zipfile module would have this feature, all other zip extractors (7z, zip(1) etc.) not. This leads to different results with different extractors and is not obvious for users. It should not matter for patool which extractor module is used. Patool usually relies on features of the archive extractor, and does not implement extra features.
- The internal zip extractor is not the preferred one because of performance, so this feature will not be used often anyway.
- We do not have any experience on how successful the character detection will be. It might be necessary to specify the character set manually anyway. There are not a lot of example zip files, since modern zip files all have unicode filenames stored.

So I think using the existing tools that fix this specific problem (see the tools mentioned above) will be a better solution instead of implementing this for patool. I am closing this issue.

**Closed by wummel** 2024-10-23 05:54 UTC

**Comment by harkabeeparolus** [comment] 2024-10-31 11:01
> * try to detect the filename encoding automatically with chardet.

I just want to mention that using chardet is probably a bad idea. The ftfy project has pretty good reasons outlined in their documentation:

* https://ftfy.readthedocs.io/en/latest/avoid.html#don-t-use-chardet
