### ISSUE TITLE
Failed with list or unpack rar archive with 7z on x86_64 system

### ISSUE THREAD

**Issue by vitlav** [wummel/patool#30] opened 2015-11-21 10:53 UTC
$ patool --verbose list a1.rar
patool: Listing a1.rar ...
patool error: error listing a1.rar: could not find an executable program to list format rar; candidates are (rar,unrar,7z),

$ strace -f patool list a1.rar
[pid 381328] stat("/usr/bin/7z", {st_mode=S_IFREG|0755, st_size=459000, ...}) = 0
[pid 381328] access("/usr/bin/7z", X_OK) = 0
[pid 381328] stat("/usr/bin/7z", {st_mode=S_IFREG|0755, st_size=459000, ...}) = 0
[pid 381328] stat("/usr/lib/p7zip/Codecs/Rar29.so", 0x7fff8a10a120) = -1 ENOENT (No such file or directory)
[pid 381328] stat("/usr/local/lib/p7zip/Codecs/Rar29.so", 0x7fff8a10a120) = -1 ENOENT (No such file or directory)
[pid 381328] write(2, "patool error:", 13patool error:) = 13

Real path on x86_64 is /usr/lib64/p7zip/Codecs/Rar29.so

**Comment by wummel** [comment] 2015-12-05 11:25
We believe that the issue you reported is fixed in the source repository of patool which can be found under:
https://github.com/wummel/patool

Changelog entry:
* Add more search paths for rar libraries.
  Patch by vitlav
  Closes: GH bug #30

Thank you for reporting the issue. It is now marked as fixed. If you believe that the issue is not fixed appropriately just add a comment to this issue.

**Comment by wummel** [comment] 2015-12-07 11:33
A new version 1.9 of patool has been released on 07.12.2015.
Therefore this bug will be closed. If you think this issue is not solved, please open a new issue.

**Closed by wummel** 2015-12-07 11:33 UTC
Labels: fixed
