### ISSUE TITLE
TypeError on unar with password

### ISSUE THREAD

**Issue by kevinmatthe** [wummel/patool#144] opened 2023-12-25 03:56 UTC
When using unar as 7-zip decompression backend program, will causing TypeError when trying to append 2 params into a cmdlist.

**Comment by kevinmatthe** [comment] 2023-12-25 04:03
https://github.com/wummel/patool/blob/8358491e7f9cabcbf3728cc490525ef925fd4cb1/patoolib/programs/unar.py#L17-L23

**Comment by kevinmatthe** [comment] 2023-12-25 04:03
#143

**Comment by kevinmatthe** [comment] 2023-12-25 04:04
@wummel Please review this issue & PR

**Comment by wummel** [comment] 2024-01-17 06:25
We believe that the issue you reported is fixed in the source repository of
patool which can be found under:
https://github.com/wummel/patool

Changelog entry:
* Fix a TypeError when using unar with passwords.
  Thanks to Kevin Matt for the patch.
  Closes: GH bug #144

Thank you for reporting the issue. It is now marked as fixed. If you believe
that the issue is not fixed appropriately just add a comment to this issue.

**Comment by wummel** [comment] 2024-01-17 06:27
A new version 2.1.0 of patool has been released on
17.01.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.

**Closed by wummel** 2024-01-17 06:27 UTC
Labels: fixed
